### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by Sourcebits-Sivanathan** [Bluedot-Innovation/PointSDK-SampleApp-iOS-Swift#1]
Hi Team,
I am getting #import <BDPointSDK.h>  file not found issues in both Objective C & Swift version of sample and also in swift version code, I am getting  another compiler error in App Delegate class.

For more info refer attached screen.

![screen shot 2015-09-03 at 1 21 00 pm](https://cloud.githubusercontent.com/assets/13116460/9653162/0d09da3c-523f-11e5-969f-425f7dffc8cd.png)

**Comment by roddy-bluedot** [comment]
Hi,

It looks like you are trying to build the 1.4 version of the Swift BDPoint Sample App utilising the 1.3 version of the SDK; 1.4 has not yet been released but will be available shortly (it is currently in testing).

Could you confirm if this is the case?

Thanks,
